### ISSUE TITLE
Figure out how to run tests on these macros!

### ISSUE THREAD

**Issue by PeterCamilleri** [PeterCamilleri/CX16#6]
I need to come up with an automated test method. To do this I need a 65C02 emulator that can be scripted and can return results to be compared with expected results.

**Comment by polluks** [comment]
Just try sim65 https://cc65.github.io/doc/sim65.html

**Comment by PeterCamilleri** [comment]
Thanks! This looks most promising!

**Comment by PeterCamilleri** [comment]
Well! I've created the test65 program as a Ruby gem. This gem has not been pushed to ruby gems org because it is too specialized to have any use beyond me.

Thank You again Stefan!

ps: Why Ruby? Because programming in Ruby makes me happy! :-)
